//! `fixed_writexml`: the FAITHFUL pretty-printer for BYTE parity with
//! canonical `xacro`.
//!
//! Canonical xacro serializes the expanded DOM with `doc.toprettyxml(indent='  ')`
//! AFTER monkey-patching `xml.dom.minidom.Element.writexml` with `fixed_writexml`
//! (`xacro/xmlutils.py`). `xmltree`'s own serializer differs in every formatting
//! detail (single line vs indented, `encoding="UTF-8"` vs none, insertion-order
//! vs alphabetical attrs, ` />` vs `/>`), so for byte parity we reimplement the
//! canonical serializer EXACTLY over the `xmltree` tree.
//!
//! Reproduced byte-for-byte from CPython 3.12 `xml.dom.minidom` + `fixed_writexml`:
//!   * the document declaration `<?xml version="1.0" ?>\n` (no encoding -> the
//!     trailing space then `?>`, exactly `Document.writexml` with `encoding=None`);
//!   * the xacro autogenerated 4-line BANNER comment block, with the source
//!     filename run through `re.sub(r'-+', '-', ...)` and `%-30s` padding
//!     (`process_file`), inserted before the root element;
//!   * `fixed_writexml` per element: `{indent}<{tag}` + ALPHABETICALLY-SORTED
//!     attributes (` name="value"`, value escaped by `_write_data`); a
//!     single-TEXT-child element collapses onto one line (`>{text}</{tag}>\n`);
//!     an element with children writes `>\n`, then each child at `indent+'  '`,
//!     SKIPPING whitespace-only text nodes, then `{indent}</{tag}>\n`; an empty
//!     element writes `/>\n`;
//!   * comments as `{indent}<!--{data}-->\n` (`Comment.writexml`);
//!   * text/attribute escaping via `_write_data`: `&`->`&amp;`, `<`->`&lt;`,
//!     `"`->`&quot;`, `>`->`&gt;` (CPython 3.12 order; `'` is NOT escaped).
//!
//! Namespace declarations (`xmlns:prefix="uri"`) are emitted as attributes named
//! `xmlns:prefix`, folded into the same alphabetically-sorted attribute set
//! (minidom stores them as attributes), so a document that keeps a non-xacro
//! namespace round-trips identically.
//!
//! KNOWN PARSER EDGE (does not affect real corpora): the `xml-rs` parser behind
//! `xmltree` reports an element's all-whitespace content as a `Whitespace` event
//! that `xmltree` drops, so a source `<tag>   </tag>` reaches this serializer with
//! NO children and renders `<tag/>`, whereas minidom keeps the text node and
//! collapses it to `<tag>   </tag>`. This only diverges for an element whose ONLY
//! content is literal whitespace text, a shape neither OpenArm nor SO-ARM
//! contains (both reach exact byte parity).

use xmltree::{Element, XMLNode};

/// The 2-space indent canonical uses (`toprettyxml(indent='  ')`).
const ADDINDENT: &str = "  ";

/// Serialize the expanded document (its top-level node list `doc_nodes`, the
/// root element plus any document-level comments that flank it, e.g. a license
/// banner) to a byte-identical canonical xacro document string.
///
/// `source_filename` is the entry file path that appears in the autogenerated
/// banner (canonical's `input_file_name`); pass the same path the caller handed to
/// the pipeline. When `None`, the banner renders `None` (matching canonical
/// `str(input_file_name)` for an absent path).
///
/// Order matches canonical `process_file`, which inserts the banner comments
/// `insertBefore(comment, doc.firstChild)`, so the output is: declaration,
/// banner (4 comments), then the document nodes in their original order (a license
/// comment before `<robot>` therefore appears after the banner, before the root).
pub fn to_canonical_string(doc_nodes: &[XMLNode], source_filename: Option<&str>) -> String {
    let mut out = String::new();
    // Document declaration: no encoding -> `<?xml version="1.0" ?>` (note the
    // space before `?>`, from `f'<?xml version="1.0" {""}?>'`).
    out.push_str("<?xml version=\"1.0\" ?>\n");

    // The autogenerated banner comments, at document indent ("") with newl "\n".
    for data in banner_comments(source_filename) {
        write_comment(&mut out, &data, "");
    }

    // The document-level nodes (comments + the root element) at indent "".
    // minidom's `Document.writexml` writes each child with the doc indent; a
    // top-level whitespace-only text node would be emitted, but a well-formed
    // document has none between the prolog and the root (xml-rs drops them).
    for node in doc_nodes {
        match node {
            XMLNode::Element(e) => write_element(&mut out, e, ""),
            XMLNode::Comment(data) => write_comment(&mut out, data, ""),
            XMLNode::Text(text) => {
                if !is_whitespace_only(text) {
                    write_text(&mut out, text, "");
                }
            }
            XMLNode::CData(data) => {
                out.push_str("<![CDATA[");
                out.push_str(data);
                out.push_str("]]>\n");
            }
            XMLNode::ProcessingInstruction(target, value) => {
                out.push_str("<?");
                out.push_str(target);
                if let Some(v) = value {
                    out.push(' ');
                    out.push_str(v);
                }
                out.push_str("?>\n");
            }
        }
    }
    out
}

/// Build the four banner comment DATA strings (the text BETWEEN `<!--` and `-->`),
/// reproducing canonical `process_file`:
/// ```python
/// [" %s " % ('=' * 83),
///  " |    This document was autogenerated by xacro from %-30s | " % re.sub(r'-+', '-', str(name)),
///  " |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED  %-30s | " % "",
///  " %s " % ('=' * 83)]
/// ```
fn banner_comments(source_filename: Option<&str>) -> [String; 4] {
    let bar = "=".repeat(83);
    // `str(input_file_name)` then collapse consecutive dashes to one.
    let raw = source_filename.unwrap_or("None");
    let name = collapse_dashes(raw);
    [
        format!(" {bar} "),
        format!(
            " |    This document was autogenerated by xacro from {} | ",
            ljust(&name, 30)
        ),
        format!(
            " |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED  {} | ",
            ljust("", 30)
        ),
        format!(" {bar} "),
    ]
}

/// `re.sub(r'-+', '-', s)`: collapse every run of one-or-more `-` to a single `-`.
fn collapse_dashes(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_dash = false;
    for c in s.chars() {
        if c == '-' {
            if !prev_dash {
                out.push('-');
            }
            prev_dash = true;
        } else {
            out.push(c);
            prev_dash = false;
        }
    }
    out
}

/// Python `'%-30s' % s`: left-justify `s` to at least `width` columns by padding
/// with trailing spaces (no truncation if already wider). Width is measured in
/// Unicode scalar values, matching Python's `len(str)`.
fn ljust(s: &str, width: usize) -> String {
    let len = s.chars().count();
    if len >= width {
        s.to_owned()
    } else {
        let mut out = String::with_capacity(s.len() + (width - len));
        out.push_str(s);
        out.extend(std::iter::repeat_n(' ', width - len));
        out
    }
}

/// `Comment.writexml`: `{indent}<!--{data}-->{newl}` (newl is always "\n" here).
fn write_comment(out: &mut String, data: &str, indent: &str) {
    out.push_str(indent);
    out.push_str("<!--");
    out.push_str(data);
    out.push_str("-->\n");
}

/// `fixed_writexml` for one element at `indent`. `newl` is always "\n".
fn write_element(out: &mut String, elt: &Element, indent: &str) {
    out.push_str(indent);
    out.push('<');
    out.push_str(&qualified_name(elt));

    // Collect attributes (including GENUINE namespace declarations as
    // `xmlns:prefix`), sorted alphabetically by name. The `xml-rs` parser behind
    // `xmltree` populates every element's namespace map with the three IMPLICIT
    // bindings the XML spec mandates be always in scope (the empty default
    // (`xmlns=""`), `xml` -> the XML namespace, and `xmlns` -> the xmlns
    // namespace), none of which is a real, source-written declaration. minidom
    // does NOT round-trip those, so emitting them would diverge; filter them out.
    let mut attrs: Vec<(String, String)> = Vec::new();
    if let Some(ns) = elt.namespaces.as_ref() {
        for (prefix, uri) in &ns.0 {
            if is_implicit_namespace(prefix, uri) {
                continue;
            }
            // The default namespace is `xmlns`; a prefixed one is `xmlns:prefix`.
            let key = if prefix.is_empty() {
                "xmlns".to_owned()
            } else {
                format!("xmlns:{prefix}")
            };
            attrs.push((key, uri.clone()));
        }
    }
    for (k, v) in elt.attributes.iter() {
        attrs.push((k.clone(), v.clone()));
    }
    attrs.sort_by(|a, b| a.0.cmp(&b.0));
    for (name, value) in &attrs {
        out.push(' ');
        out.push_str(name);
        out.push_str("=\"");
        write_data(out, value);
        out.push('"');
    }

    // Partition children: minidom's `childNodes` includes text/comment/element.
    // `fixed_writexml` checks `if self.childNodes:` (any child at all). The
    // single-text-collapse only fires for EXACTLY ONE child that is a TEXT node.
    if elt.children.is_empty() {
        out.push_str("/>\n");
        return;
    }

    if elt.children.len() == 1 {
        if let XMLNode::Text(text) = &elt.children[0] {
            // Single text child: `>{text}</{tag}>\n` (text escaped, no indent/newl).
            out.push('>');
            write_data(out, text);
            out.push_str("</");
            out.push_str(&qualified_name(elt));
            out.push_str(">\n");
            return;
        }
    }

    // General case: `>\n`, then each child at `indent+'  '`, skipping
    // whitespace-only text nodes, then `{indent}</{tag}>\n`.
    out.push_str(">\n");
    let child_indent = format!("{indent}{ADDINDENT}");
    for child in &elt.children {
        match child {
            XMLNode::Element(e) => write_element(out, e, &child_indent),
            XMLNode::Comment(data) => write_comment(out, data, &child_indent),
            XMLNode::Text(text) => {
                // Skip whitespace-only / empty text nodes (canonical
                // `not node.data or node.data.isspace()`).
                if !is_whitespace_only(text) {
                    write_text(out, text, &child_indent);
                }
            }
            XMLNode::CData(data) => {
                // minidom emits CDATA verbatim; rare in URDF, kept faithful.
                out.push_str(&child_indent);
                out.push_str("<![CDATA[");
                out.push_str(data);
                out.push_str("]]>\n");
            }
            XMLNode::ProcessingInstruction(target, value) => {
                out.push_str(&child_indent);
                out.push_str("<?");
                out.push_str(target);
                if let Some(v) = value {
                    out.push(' ');
                    out.push_str(v);
                }
                out.push_str("?>\n");
            }
        }
    }
    out.push_str(indent);
    out.push_str("</");
    out.push_str(&qualified_name(elt));
    out.push_str(">\n");
}

/// `Text.writexml`: `_write_data(writer, "{indent}{data}{newl}")`, i.e. the
/// indent + newline are INSIDE the escaped payload (so they are not escaped, being
/// whitespace, but the data is). Faithful: escape only `data`, surround with the
/// already-safe indent/newl.
fn write_text(out: &mut String, data: &str, indent: &str) {
    out.push_str(indent);
    write_data(out, data);
    out.push('\n');
}

/// `_write_data` (CPython 3.12): escape `&`, `<`, `"`, `>` in THAT order. `'` is
/// NOT escaped. Used for both attribute values and text.
fn write_data(out: &mut String, data: &str) {
    for c in data.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '"' => out.push_str("&quot;"),
            '>' => out.push_str("&gt;"),
            other => out.push(other),
        }
    }
}

/// The element's serialized tag name: `prefix:name` if it carries a prefix, else
/// `name`. (After xacro expansion the output is unprefixed, but a surviving
/// non-xacro prefix must round-trip.)
fn qualified_name(elt: &Element) -> String {
    match elt.prefix.as_deref() {
        Some(p) if !p.is_empty() => format!("{p}:{}", elt.name),
        _ => elt.name.clone(),
    }
}

/// The three namespace bindings the XML spec keeps implicitly in scope, which the
/// `xml-rs` parser materializes onto every element but which are NOT real
/// source-written declarations (minidom does not round-trip them): the empty
/// default `xmlns=""`, the reserved `xml` prefix, and the `xmlns` prefix itself.
fn is_implicit_namespace(prefix: &str, uri: &str) -> bool {
    (prefix.is_empty() && uri.is_empty())
        || (prefix == "xml" && uri == "http://www.w3.org/XML/1998/namespace")
        || (prefix == "xmlns" && uri == "http://www.w3.org/2000/xmlns/")
}

/// Is `s` empty or all-whitespace? (`not node.data or node.data.isspace()`.)
/// Python's `str.isspace()` is true for a NON-empty string of whitespace; an
/// empty string is caught by `not node.data`. So: empty OR all-whitespace.
fn is_whitespace_only(s: &str) -> bool {
    s.is_empty() || s.chars().all(char::is_whitespace)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(xml: &str) -> Vec<XMLNode> {
        Element::parse_all(xml.as_bytes()).unwrap()
    }

    #[test]
    fn declaration_and_banner() {
        let root = parse("<robot name=\"r\"/>");
        let s = to_canonical_string(&root, Some("/path/to/r.xacro"));
        assert!(s.starts_with("<?xml version=\"1.0\" ?>\n"));
        assert!(s.contains("autogenerated by xacro from /path/to/r.xacro "));
        // 83 '=' bars.
        assert!(s.contains(&format!(" {} ", "=".repeat(83))));
        // empty element -> `/>`.
        assert!(s.contains("<robot name=\"r\"/>\n"));
    }

    #[test]
    fn sorted_attrs_and_collapse_and_skip_ws() {
        let root = parse("<a z=\"1\" m=\"2\"><b>text</b><c>  </c><d><e/></d></a>");
        let s = to_canonical_string(&root, None);
        // attrs sorted: m before z.
        assert!(s.contains("<a m=\"2\" z=\"1\">"));
        // single text child collapses.
        assert!(s.contains("  <b>text</b>\n"));
        // `<c>  </c>`: the underlying `xml-rs` parser emits the all-whitespace
        // content as a `Whitespace` event that `xmltree` DROPS, so `<c>` reaches the
        // serializer with NO children and renders `<c/>`. (minidom would keep the
        // text node and collapse it to `<c>  </c>`; this is a known parser-level
        // whitespace edge that does not occur in real URDF/xacro corpora; both
        // OpenArm and SO-ARM reach BYTE parity. See module note.)
        assert!(s.contains("  <c/>\n"));
        // nested element indented 2 levels.
        assert!(s.contains("  <d>\n    <e/>\n  </d>\n"));
    }

    #[test]
    fn escaping() {
        let root = parse("<a t=\"a&amp;b&lt;c&gt;d&quot;e\">x&amp;y&lt;z</a>");
        let s = to_canonical_string(&root, None);
        assert!(s.contains("t=\"a&amp;b&lt;c&gt;d&quot;e\""));
        assert!(s.contains(">x&amp;y&lt;z</a>"));
    }

    #[test]
    fn dash_collapse_in_banner() {
        let root = parse("<r/>");
        let s = to_canonical_string(&root, Some("a---b--c.xacro"));
        // consecutive dashes collapsed to single (XML-comment-safe).
        assert!(s.contains("xacro from a-b-c.xacro"));
        assert!(!s.contains("a---b"));
    }
}
